import { z } from 'zod';
import type { OpenAPIRegistry } from '@asteasolutions/zod-to-openapi';
import {
  activeSchema, auditListQuerySchema, cursorQuerySchema, customerListQuerySchema, dashboardQuerySchema,
  expectedVersionSchema, idParamsSchema, imageOrderSchema, imagePatchSchema, imageUploadFieldsSchema, inventoryAdjustmentSchema,
  loyaltyProgramWriteSchema, transferSettingsWriteSchema, orderActionSchema, orderListQuerySchema, orderParamsSchema, orderTransitionSchema, paymentsQuerySchema,
  pickupPointWriteSchema, productImageParamsSchema, productListQuerySchema, productPatchSchema,
  productWriteSchema, refundSchema, shippingZoneWriteSchema, supplierActiveSchema, supplierListQuerySchema,
  supplierPatchSchema, supplierWriteSchema, transferReceiptParamsSchema, transferReviewSchema,
  tcgdexCardParamsSchema, tcgdexImageImportSchema, tcgdexSearchQuerySchema,
  newsListQuerySchema, newsWriteSchema, newsPatchSchema,
  adminActiveMutationDataSchema, adminAuditEntrySchema, adminCustomerDetailDataSchema, adminCustomerSummarySchema,
  adminDashboardDataSchema, adminEnvelopeSchema, adminFulfillmentDataSchema, adminFullRefundDataSchema,
  adminInventoryAdjustmentSchema, adminInventoryMutationDataSchema, adminLoyaltyProgramSchema, adminOrderDetailDataSchema, adminOrderSchema,
  adminOrderStatusDataSchema, adminPickupPointResultDataSchema, adminProductDetailDataSchema, adminProductImageOrderDataSchema,
  adminProductImagesDataSchema, adminProductImageUpdateDataSchema, adminProductSchema, adminProductStatusDataSchema,
  adminShippingZoneResultDataSchema, adminTransferReviewDataSchema,
  adminSupplierActiveMutationDataSchema, adminSupplierDetailDataSchema, adminSupplierSchema, adminTcgdexCardDataSchema, adminTransferSettingsSchema,
  adminTcgdexCardSummarySchema, adminNewsSchema, adminNewsDetailDataSchema,
} from '../backoffice/index.js';

type Options = { problemSchema: z.ZodType; moneySchema: z.ZodType };

export function registerAdminCmsPaths(registry: OpenAPIRegistry, { problemSchema, moneySchema }: Options): void {
  const dateTimeSchema = z.string().datetime();
  const csrf = z.object({ 'x-csrf-token': z.string().min(32) });
  const security = [{ adminCookie: [] }];
  const envelope = adminEnvelopeSchema;
  const errors = {
    400: { description: 'Invalid request', content: { 'application/json': { schema: problemSchema } } },
    401: { description: 'Admin session missing, idle or expired', content: { 'application/json': { schema: problemSchema } } },
    403: { description: 'Invalid admin CSRF token', content: { 'application/json': { schema: problemSchema } } },
    404: { description: 'Resource not found', content: { 'application/json': { schema: problemSchema } } },
    409: { description: 'Version, state or inventory conflict', content: { 'application/json': { schema: problemSchema } } },
  };
  const ok = (description: string, data: z.ZodTypeAny) => ({ 200: { description, content: { 'application/json': { schema: envelope(data) } } }, ...errors });
  const created = (description: string, data: z.ZodTypeAny) => ({ 201: { description, content: { 'application/json': { schema: envelope(data) } } }, ...errors });
  const json = (schema: z.ZodType) => ({ required: true, content: { 'application/json': { schema } } });

  registry.register('AdminMoney', moneySchema);
  registry.register('AdminProductWrite', productWriteSchema);
  registry.register('AdminProductPatch', productPatchSchema);
  registry.register('AdminOrderTransition', orderTransitionSchema);
  registry.register('AdminShippingZoneWrite', shippingZoneWriteSchema);
  registry.register('AdminPickupPointWrite', pickupPointWriteSchema);
  registry.register('AdminSupplierWrite', supplierWriteSchema);
  registry.register('AdminSupplierPatch', supplierPatchSchema);
  registry.register('AdminLoyaltyProgramWrite', loyaltyProgramWriteSchema);
  registry.register('AdminLoyaltyProgram', adminLoyaltyProgramSchema);
  registry.register('AdminTransferSettings', adminTransferSettingsSchema);
  registry.register('AdminNews', adminNewsSchema);
  registry.register('AdminNewsWrite', newsWriteSchema);
  registry.register('AdminNewsPatch', newsPatchSchema);
  const affiliateIdParams = z.object({ id: z.string().uuid() });
  const affiliateAdminProfile = z.object({ id: z.string().uuid(), userId: z.string().uuid(), publicName: z.string(), status: z.enum(['ACTIVE', 'SUSPENDED']), version: z.number().int() }).passthrough();
  const affiliateReview = z.object({ expectedVersion: z.number().int().min(1), decision: z.enum(['APPROVED', 'CHANGES_REQUESTED', 'REJECTED']), note: z.string().max(500).optional() });
  const affiliatePage = z.object({ page: z.number().int(), pageSize: z.number().int(), total: z.number().int(), totalPages: z.number().int() });
  const sellerOrderStatus = z.enum(['PENDING_PAYMENT', 'PAID', 'PREPARING', 'READY_FOR_PICKUP', 'PICKED_UP', 'SHIPPED', 'COMPLETED', 'CANCELLATION_REQUESTED', 'CANCELLED', 'DISPUTED', 'REFUNDED']);
  const affiliateSellerOrder = z.object({ id: z.string().uuid(), number: z.string(), sellerType: z.enum(['STORE', 'AFFILIATE']), affiliateId: z.string().uuid().nullable(), sellerName: z.string(), status: sellerOrderStatus, version: z.number().int(), subtotalMinor: z.string(), shippingMinor: z.string(), commissionMinor: z.string(), sellerNetMinor: z.string(), allowedActions: z.array(z.string()), items: z.array(z.object({ id: z.string().uuid(), productId: z.string().uuid(), productName: z.string(), quantity: z.number().int(), unitPriceMinor: z.string(), lineTotalMinor: z.string() }).passthrough()), statusHistory: z.array(z.object({ id: z.string().uuid(), fromStatus: sellerOrderStatus.nullable(), toStatus: sellerOrderStatus, note: z.string().nullable(), createdAt: dateTimeSchema }).passthrough()).default([]) }).passthrough();
  const affiliateListing = z.object({ id: z.string().uuid(), status: z.enum(['DRAFT', 'PENDING_REVIEW', 'CHANGES_REQUESTED', 'REJECTED', 'APPROVED']), reviewNote: z.string().nullable(), product: z.object({ id: z.string().uuid(), name: z.string(), priceMinor: z.string(), status: z.string(), version: z.number().int() }).passthrough() }).passthrough();
  const affiliatePayout = z.object({ id: z.string().uuid(), amountMinor: z.string(), status: z.enum(['REQUESTED', 'PROCESSING', 'PAID', 'REJECTED']), destinationLast4: z.string().nullable(), externalReference: z.string().nullable(), version: z.number().int() }).passthrough();
  const affiliateIssue = z.object({ id: z.string().uuid(), status: z.string(), reason: z.string(), previousStatus: sellerOrderStatus, createdAt: dateTimeSchema }).passthrough();
  const affiliateCancellation = z.object({ id: z.string().uuid(), status: z.enum(['REQUESTED', 'APPROVED', 'REJECTED']), reason: z.string(), previousStatus: sellerOrderStatus, createdAt: dateTimeSchema }).passthrough();
  const affiliateSettings = z.object({ id: z.string(), commissionBps: z.number().int(), autoCompleteDays: z.number().int().positive(), version: z.number().int() }).passthrough();

  registry.registerPath({ method: 'get', path: '/api/v2/admin/dashboard', tags: ['Admin dashboard'], summary: 'Read operational and commercial metrics', security, request: { query: dashboardQuerySchema }, responses: ok('Dashboard for the selected date range', adminDashboardDataSchema) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/loyalty/config', tags: ['Admin loyalty'], summary: 'Read the configurable earning and redemption rules', security, responses: ok('Current loyalty program configuration', adminLoyaltyProgramSchema) });
  registry.registerPath({ method: 'patch', path: '/api/v2/admin/loyalty/config', tags: ['Admin loyalty'], summary: 'Update loyalty rules using optimistic concurrency', security, request: { headers: csrf, body: json(loyaltyProgramWriteSchema) }, responses: ok('Loyalty program configuration updated', adminLoyaltyProgramSchema) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/config/transfer', tags: ['Admin configuration'], summary: 'Read bank transfer configuration', security, responses: ok('Current bank transfer configuration', adminTransferSettingsSchema) });
  registry.registerPath({ method: 'patch', path: '/api/v2/admin/config/transfer', tags: ['Admin configuration'], summary: 'Update bank transfer configuration using optimistic concurrency', security, request: { headers: csrf, body: json(transferSettingsWriteSchema) }, responses: ok('Bank transfer configuration updated', adminTransferSettingsSchema) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/affiliates/summary', tags: ['Admin affiliates'], summary: 'Read affiliate commercial metrics and attention queues', security, responses: ok('Affiliate summary', z.object({ affiliates: z.number().int(), listings: z.array(z.record(z.string(), z.unknown())), orders: z.array(z.record(z.string(), z.unknown())), queues: z.object({ issues: z.number().int(), cancellations: z.number().int(), payouts: z.number().int() }), obligationsMinor: z.string() })) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/affiliates', tags: ['Admin affiliates'], summary: 'List affiliate profiles and seller activity', security, request: { query: z.object({ page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(25), search: z.string().optional(), status: z.enum(['ACTIVE', 'SUSPENDED']).optional() }) }, responses: ok('Affiliate profiles', affiliatePage.extend({ items: z.array(affiliateAdminProfile) })) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/affiliates', tags: ['Admin affiliates'], summary: 'Enable an existing customer as an affiliate', security, request: { headers: csrf, body: json(z.object({ userId: z.string().uuid(), publicName: z.string().min(2).max(120), contactPhone: z.string().max(50).nullable().optional(), payoutAccount: z.string().max(500).nullable().optional() })) }, responses: created('Affiliate created', affiliateAdminProfile) });
  registry.registerPath({ method: 'patch', path: '/api/v2/admin/affiliates/{id}', tags: ['Admin affiliates'], summary: 'Edit, suspend or reactivate an affiliate using optimistic concurrency', security, request: { params: affiliateIdParams, headers: csrf, body: json(z.object({ expectedVersion: z.number().int().min(1), publicName: z.string().max(120).optional(), status: z.enum(['ACTIVE', 'SUSPENDED']).optional(), commissionBpsOverride: z.number().int().min(0).max(10000).nullable().optional() })) }, responses: ok('Affiliate updated', affiliateAdminProfile) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/affiliates/{id}', tags: ['Admin affiliates'], summary: 'Read the complete affiliate operational file', security, request: { params: affiliateIdParams }, responses: ok('Affiliate detail', z.object({ affiliate: affiliateAdminProfile, counts: z.record(z.string(), z.number().int()), balance: z.record(z.string(), z.object({ amountMinor: z.string(), currency: z.literal('USD') })), listings: z.array(affiliateListing), orders: z.array(affiliateSellerOrder), payouts: z.array(affiliatePayout) })) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/affiliates/listings', tags: ['Admin affiliates'], summary: 'List affiliate publications with search and editorial filters', security, request: { query: z.object({ page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(25), search: z.string().optional(), status: z.enum(['DRAFT', 'PENDING_REVIEW', 'CHANGES_REQUESTED', 'REJECTED', 'APPROVED']).optional() }) }, responses: ok('Affiliate listings', affiliatePage.extend({ items: z.array(affiliateListing) })) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/affiliates/listings/{id}', tags: ['Admin affiliates'], summary: 'Preview one affiliate publication', security, request: { params: affiliateIdParams }, responses: ok('Affiliate listing detail', z.object({ listing: affiliateListing })) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/affiliates/listings/{id}/review', tags: ['Admin affiliates'], summary: 'Approve, reject or request changes on an affiliate listing', security, request: { params: affiliateIdParams, headers: csrf, body: json(affiliateReview) }, responses: ok('Affiliate listing reviewed', z.object({ id: z.string().uuid(), status: z.string(), productStatus: z.string(), version: z.number().int() })) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/affiliates/seller-orders', tags: ['Admin affiliates'], summary: 'List seller suborders across the marketplace', security, request: { query: z.object({ page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(25), search: z.string().optional(), sellerType: z.enum(['STORE', 'AFFILIATE']).optional(), status: sellerOrderStatus.optional() }) }, responses: ok('Seller orders', affiliatePage.extend({ items: z.array(affiliateSellerOrder) })) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/affiliates/seller-orders/{id}', tags: ['Admin affiliates'], summary: 'Read a seller suborder with timeline, incidents, cancellations and refunds', security, request: { params: affiliateIdParams }, responses: ok('Seller order detail', z.object({ order: affiliateSellerOrder.extend({ parentOrder: z.record(z.string(), z.unknown()) }) })) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/affiliates/seller-orders/{id}/status', tags: ['Admin affiliates'], summary: 'Execute an exceptional seller-order transition', security, request: { params: affiliateIdParams, headers: csrf, body: json(z.object({ expectedVersion: z.number().int().min(1), status: sellerOrderStatus, note: z.string().min(3).max(500), carrier: z.string().max(100).nullable().optional(), trackingCode: z.string().max(120).nullable().optional() })) }, responses: ok('Seller order transitioned', z.object({ id: z.string().uuid(), status: sellerOrderStatus, version: z.number().int(), allowedActions: z.array(z.string()) })) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/affiliates/seller-orders/{id}/refund', tags: ['Admin affiliates'], summary: 'Register an external refund, reverse affiliate liability and optionally restock products', security, request: { params: affiliateIdParams, headers: csrf, body: json(z.object({ expectedVersion: z.number().int().min(1), amountMinor: z.coerce.bigint().positive(), subtotalMinor: z.coerce.bigint().nonnegative().optional(), shippingMinor: z.coerce.bigint().nonnegative().optional(), reason: z.string().min(3).max(500), externalReference: z.string().min(2).max(150), restock: z.boolean().optional(), lines: z.array(z.object({ orderItemId: z.string().uuid(), quantity: z.number().int().positive(), amountMinor: z.coerce.bigint().positive() })).max(100).optional() })) }, responses: ok('Seller order refunded', z.object({ id: z.string().uuid(), status: z.literal('REFUNDED'), version: z.number().int(), refundId: z.string().uuid(), allowedActions: z.array(z.string()) })) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/affiliates/issues', tags: ['Admin affiliates'], summary: 'List open and resolved affiliate incidents', security, request: { query: z.object({ page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(25), status: z.string().optional() }) }, responses: ok('Affiliate incidents', affiliatePage.extend({ items: z.array(affiliateIssue) })) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/affiliates/issues/{id}', tags: ['Admin affiliates'], summary: 'Read an incident before resolution', security, request: { params: affiliateIdParams }, responses: ok('Affiliate incident detail', z.object({ issue: affiliateIssue })) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/affiliates/issues/{id}/resolve', tags: ['Admin affiliates'], summary: 'Continue, complete or refund an incident with an audit reason', security, request: { params: affiliateIdParams, headers: csrf, body: json(z.object({ expectedVersion: z.number().int().min(1), decision: z.enum(['CONTINUE', 'COMPLETE', 'PARTIAL_REFUND', 'FULL_REFUND']), note: z.string().min(3).max(500), refundAmountMinor: z.coerce.bigint().positive().optional(), refundSubtotalMinor: z.coerce.bigint().nonnegative().optional(), refundShippingMinor: z.coerce.bigint().nonnegative().optional(), externalReference: z.string().min(2).max(150).optional(), restock: z.boolean().optional() })) }, responses: ok('Incident resolved', z.object({ id: z.string().uuid(), status: z.string() })) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/affiliates/cancellations', tags: ['Admin affiliates'], summary: 'List open and resolved cancellation requests', security, request: { query: z.object({ page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(25), status: z.enum(['REQUESTED', 'APPROVED', 'REJECTED']).optional() }) }, responses: ok('Affiliate cancellations', affiliatePage.extend({ items: z.array(affiliateCancellation) })) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/affiliates/cancellations/{id}', tags: ['Admin affiliates'], summary: 'Read a cancellation request before resolution', security, request: { params: affiliateIdParams }, responses: ok('Affiliate cancellation detail', z.object({ cancellation: affiliateCancellation })) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/affiliates/cancellations/{id}/resolve', tags: ['Admin affiliates'], summary: 'Approve or reject a cancellation and register an external refund', security, request: { params: affiliateIdParams, headers: csrf, body: json(z.object({ expectedVersion: z.number().int().min(1), decision: z.enum(['APPROVED', 'REJECTED']), note: z.string().min(3).max(500), refundAmountMinor: z.coerce.bigint().positive().optional(), externalReference: z.string().min(2).max(150).optional(), restock: z.boolean().optional() })) }, responses: ok('Cancellation resolved', z.object({ id: z.string().uuid(), status: z.string() })) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/affiliates/payouts', tags: ['Admin affiliates'], summary: 'List affiliate payout requests', security, request: { query: z.object({ page: z.coerce.number().int().min(1).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(25), status: z.enum(['REQUESTED', 'PROCESSING', 'PAID', 'REJECTED']).optional() }) }, responses: ok('Affiliate payout requests', affiliatePage.extend({ items: z.array(affiliatePayout) })) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/affiliates/payouts/{id}', tags: ['Admin affiliates'], summary: 'Read a payout with masked destination and ledger entries', security, request: { params: affiliateIdParams }, responses: ok('Affiliate payout detail', z.object({ payout: affiliatePayout, ledger: z.array(z.record(z.string(), z.unknown())) })) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/affiliates/payouts/{id}/reveal-destination', tags: ['Admin affiliates'], summary: 'Reveal a payout destination for sixty seconds and audit the action', security, request: { params: affiliateIdParams, headers: csrf }, responses: ok('Payout destination revealed', z.object({ destination: z.string(), expiresInSeconds: z.number().int() })) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/affiliates/payouts/{id}/process', tags: ['Admin affiliates'], summary: 'Move a payout through processing and record an external payment or rejection', security, request: { params: affiliateIdParams, headers: csrf, body: json(z.object({ expectedVersion: z.number().int().min(1), status: z.enum(['PROCESSING', 'PAID', 'REJECTED']), externalReference: z.string().min(2).max(150), note: z.string().max(500).optional() })) }, responses: ok('Payout processed', z.object({ id: z.string().uuid(), status: z.enum(['REQUESTED', 'PROCESSING', 'PAID', 'REJECTED']), version: z.number().int() })) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/affiliates/settings', tags: ['Admin affiliates'], summary: 'Read the versioned global affiliate commission and auto-completion policy', security, responses: ok('Affiliate settings', affiliateSettings) });
  registry.registerPath({ method: 'patch', path: '/api/v2/admin/affiliates/settings', tags: ['Admin affiliates'], summary: 'Update the global commission and automatic completion window', security, request: { headers: csrf, body: json(z.object({ expectedVersion: z.number().int().min(1), commissionBps: z.number().int().min(0).max(10000), autoCompleteDays: z.number().int().min(1).max(90) })) }, responses: ok('Affiliate settings updated', affiliateSettings) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/affiliates/ledger-adjustments', tags: ['Admin affiliates'], summary: 'Apply an audited manual affiliate ledger adjustment', security, request: { headers: csrf, body: json(z.object({ affiliateId: z.string().uuid(), bucket: z.enum(['PENDING', 'AVAILABLE', 'RESERVED', 'PAID']), amountMinor: z.coerce.bigint(), note: z.string().min(3).max(500), dedupeKey: z.string().min(3).max(150).optional() })) }, responses: ok('Affiliate ledger adjusted', z.record(z.string(), z.unknown())) });

  registry.registerPath({ method: 'get', path: '/api/v2/admin/tcgdex/cards', tags: ['Admin products'], summary: 'Search the TCGdex card catalog for product autofill', security, request: { query: tcgdexSearchQuerySchema }, responses: ok('Matching TCGdex cards', z.array(adminTcgdexCardSummarySchema)) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/tcgdex/cards/{id}', tags: ['Admin products'], summary: 'Read a full TCGdex card for product autofill', security, request: { params: tcgdexCardParamsSchema }, responses: ok('TCGdex card details', adminTcgdexCardDataSchema) });

  registry.registerPath({ method: 'get', path: '/api/v2/admin/products', tags: ['Admin products'], summary: 'List products in every publication state', security, request: { query: productListQuerySchema }, responses: ok('Cursor page of products', z.array(adminProductSchema)) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/products', tags: ['Admin products'], summary: 'Create a draft product and initial inventory', security, request: { headers: csrf, body: json(productWriteSchema) }, responses: created('Draft product created', adminProductDetailDataSchema) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/products/{id}', tags: ['Admin products'], summary: 'Read complete administrative product data', security, request: { params: idParamsSchema }, responses: ok('Administrative product detail', adminProductDetailDataSchema) });
  registry.registerPath({ method: 'patch', path: '/api/v2/admin/products/{id}', tags: ['Admin products'], summary: 'Edit a product using optimistic concurrency', security, request: { params: idParamsSchema, headers: csrf, body: json(productPatchSchema) }, responses: ok('Product updated', adminProductDetailDataSchema) });
  for (const action of ['publish', 'archive'] as const) {
    registry.registerPath({ method: 'post', path: `/api/v2/admin/products/{id}/${action}`, tags: ['Admin products'], summary: `${action === 'publish' ? 'Publish' : 'Archive'} a product using optimistic concurrency`, security, request: { params: idParamsSchema, headers: csrf, body: json(expectedVersionSchema) }, responses: ok(`Product ${action === 'publish' ? 'published' : 'archived'}`, adminProductStatusDataSchema) });
  }
  registry.registerPath({
    method: 'post', path: '/api/v2/admin/products/{id}/images', tags: ['Admin products'], summary: 'Upload up to eight active product images', security,
    request: { params: idParamsSchema, headers: csrf, body: { required: true, content: { 'multipart/form-data': { schema: imageUploadFieldsSchema.extend({ images: z.array(z.string().openapi({ format: 'binary' })).min(1).max(8) }) } } } },
    responses: created('Images decoded, sanitized and attached', adminProductImagesDataSchema),
  });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/products/{id}/tcgdex-image', tags: ['Admin products'], summary: 'Download, sanitize and attach an official TCGdex card image', security, request: { params: idParamsSchema, headers: csrf, body: json(tcgdexImageImportSchema) }, responses: created('TCGdex image attached', adminProductImagesDataSchema) });
  registry.registerPath({ method: 'patch', path: '/api/v2/admin/products/{id}/images/{imageId}', tags: ['Admin products'], summary: 'Update accessible image text', security, request: { params: productImageParamsSchema, headers: csrf, body: json(imagePatchSchema) }, responses: ok('Image metadata updated', adminProductImageUpdateDataSchema) });
  registry.registerPath({ method: 'put', path: '/api/v2/admin/products/{id}/images/order', tags: ['Admin products'], summary: 'Reorder all active images; position zero is the cover', security, request: { params: idParamsSchema, headers: csrf, body: json(imageOrderSchema) }, responses: ok('Images reordered', adminProductImageOrderDataSchema) });
  registry.registerPath({ method: 'delete', path: '/api/v2/admin/products/{id}/images/{imageId}', tags: ['Admin products'], summary: 'Retire an image using optimistic concurrency while retaining referenced order media', security, request: { params: productImageParamsSchema, headers: csrf, body: json(expectedVersionSchema) }, responses: { 204: { description: 'Image retired and durable cleanup scheduled' }, ...errors } });

  registry.registerPath({ method: 'get', path: '/api/v2/admin/inventory', tags: ['Admin inventory'], summary: 'List on-hand, reserved and available inventory', security, request: { query: productListQuerySchema }, responses: ok('Cursor page of inventory', z.array(adminProductSchema)) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/products/{id}/inventory-adjustments', tags: ['Admin inventory'], summary: 'List immutable stock adjustments', security, request: { params: idParamsSchema, query: cursorQuerySchema }, responses: ok('Cursor page of stock adjustments', z.array(adminInventoryAdjustmentSchema)) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/products/{id}/inventory-adjustment', tags: ['Admin inventory'], summary: 'Apply a reasoned stock delta without changing reservations', security, request: { params: idParamsSchema, headers: csrf, body: json(inventoryAdjustmentSchema) }, responses: ok('Inventory adjusted', adminInventoryMutationDataSchema) });

  registry.registerPath({ method: 'get', path: '/api/v2/admin/suppliers', tags: ['Admin suppliers'], summary: 'List supplier directory entries', security, request: { query: supplierListQuerySchema }, responses: ok('Cursor page of suppliers', z.array(adminSupplierSchema)) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/suppliers/{id}', tags: ['Admin suppliers'], summary: 'Read supplier details', security, request: { params: idParamsSchema }, responses: ok('Supplier detail', adminSupplierDetailDataSchema) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/suppliers', tags: ['Admin suppliers'], summary: 'Create an active supplier', security, request: { headers: csrf, body: json(supplierWriteSchema) }, responses: created('Supplier created', adminSupplierDetailDataSchema) });
  registry.registerPath({ method: 'patch', path: '/api/v2/admin/suppliers/{id}', tags: ['Admin suppliers'], summary: 'Edit a supplier using optimistic concurrency', security, request: { params: idParamsSchema, headers: csrf, body: json(supplierPatchSchema) }, responses: ok('Supplier updated', adminSupplierDetailDataSchema) });
  registry.registerPath({ method: 'patch', path: '/api/v2/admin/suppliers/{id}/active', tags: ['Admin suppliers'], summary: 'Activate or deactivate a supplier without deleting history', security, request: { params: idParamsSchema, headers: csrf, body: json(supplierActiveSchema) }, responses: ok('Supplier availability changed', adminSupplierActiveMutationDataSchema) });

  registry.registerPath({ method: 'get', path: '/api/v2/admin/news', tags: ['Admin news'], summary: 'List all news items and publication states', security, request: { query: newsListQuerySchema }, responses: ok('Cursor page of news items', z.array(adminNewsSchema)) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/news/{id}', tags: ['Admin news'], summary: 'Read an administrative news item', security, request: { params: idParamsSchema }, responses: ok('News item detail', adminNewsDetailDataSchema) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/news', tags: ['Admin news'], summary: 'Create an inactive news item', security, request: { headers: csrf, body: json(newsWriteSchema) }, responses: created('News item created', adminNewsDetailDataSchema) });
  registry.registerPath({ method: 'patch', path: '/api/v2/admin/news/{id}', tags: ['Admin news'], summary: 'Edit a news item using optimistic concurrency', security, request: { params: idParamsSchema, headers: csrf, body: json(newsPatchSchema) }, responses: ok('News item updated', adminNewsDetailDataSchema) });
  registry.registerPath({ method: 'delete', path: '/api/v2/admin/news/{id}', tags: ['Admin news'], summary: 'Permanently delete a news item', security, request: { params: idParamsSchema, headers: csrf, body: json(expectedVersionSchema) }, responses: { 204: { description: 'News item deleted' }, ...errors } });

  registry.registerPath({ method: 'get', path: '/api/v2/admin/orders', tags: ['Admin orders'], summary: 'List and filter orders', security, request: { query: orderListQuerySchema }, responses: ok('Cursor page of orders', z.array(adminOrderSchema)) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/orders/{number}', tags: ['Admin orders'], summary: 'Read immutable snapshots, timeline and allowed actions', security, request: { params: orderParamsSchema }, responses: ok('Administrative order detail', adminOrderDetailDataSchema) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/orders/{number}/cancel', tags: ['Admin orders'], summary: 'Cancel a pending order and release reservations exactly once', security, request: { params: orderParamsSchema, headers: csrf, body: json(orderActionSchema) }, responses: ok('Order cancelled', adminOrderStatusDataSchema) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/orders/{number}/transition', tags: ['Admin orders'], summary: 'Apply a permitted fulfillment transition', security, request: { params: orderParamsSchema, headers: csrf, body: json(orderTransitionSchema) }, responses: ok('Order status changed', adminOrderStatusDataSchema) });
  registry.registerPath({ method: 'patch', path: '/api/v2/admin/orders/{number}/status', tags: ['Admin orders'], summary: 'Compatibility alias for an order transition', deprecated: true, security, request: { params: orderParamsSchema, headers: csrf, body: json(orderTransitionSchema) }, responses: ok('Order status changed', adminOrderStatusDataSchema) });
  for (const decision of ['approve', 'reject'] as const) {
    registry.registerPath({ method: 'post', path: `/api/v2/admin/orders/{number}/transfer-receipts/{receiptId}/${decision}`, tags: ['Admin payments'], summary: `${decision === 'approve' ? 'Approve' : 'Reject'} a specific transfer receipt`, security, request: { params: transferReceiptParamsSchema, headers: csrf, body: json(transferReviewSchema) }, responses: ok(`Transfer receipt ${decision === 'approve' ? 'approved' : 'rejected'}`, adminTransferReviewDataSchema) });
  }
  registry.registerPath({ method: 'post', path: '/api/v2/admin/orders/{number}/late-payment/fulfill', tags: ['Admin payments'], summary: 'Accept a canonical late payment after atomically reacquiring stock', security, request: { params: orderParamsSchema, headers: csrf, body: json(expectedVersionSchema) }, responses: ok('Late payment accepted for fulfillment', adminOrderStatusDataSchema) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/orders/{number}/refund', tags: ['Admin payments'], summary: 'Record one external full refund without replenishing stock', security, request: { params: orderParamsSchema, headers: csrf, body: json(refundSchema) }, responses: created('Full refund recorded', adminFullRefundDataSchema) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/payments', tags: ['Admin payments'], summary: 'List payments or an operational review queue', security, request: { query: paymentsQuerySchema }, responses: ok('Cursor page of payments and orders', z.array(adminOrderSchema)) });

  registry.registerPath({ method: 'get', path: '/api/v2/admin/fulfillment', tags: ['Admin fulfillment'], summary: 'List all zones, rates and pickup points', security, responses: ok('Fulfillment configuration', adminFulfillmentDataSchema) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/fulfillment/shipping-zones', tags: ['Admin fulfillment'], summary: 'Create a shipping zone and rates', security, request: { headers: csrf, body: json(shippingZoneWriteSchema) }, responses: created('Shipping zone created', adminShippingZoneResultDataSchema) });
  registry.registerPath({ method: 'patch', path: '/api/v2/admin/fulfillment/shipping-zones/{id}', tags: ['Admin fulfillment'], summary: 'Replace a shipping zone configuration', security, request: { params: idParamsSchema, headers: csrf, body: json(shippingZoneWriteSchema) }, responses: ok('Shipping zone updated', adminShippingZoneResultDataSchema) });
  registry.registerPath({ method: 'patch', path: '/api/v2/admin/fulfillment/shipping-zones/{id}/active', tags: ['Admin fulfillment'], summary: 'Activate or deactivate a shipping zone', security, request: { params: idParamsSchema, headers: csrf, body: json(activeSchema) }, responses: ok('Shipping zone availability changed', adminActiveMutationDataSchema) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/fulfillment/pickup-points', tags: ['Admin fulfillment'], summary: 'Create a pickup point', security, request: { headers: csrf, body: json(pickupPointWriteSchema) }, responses: created('Pickup point created', adminPickupPointResultDataSchema) });
  registry.registerPath({ method: 'patch', path: '/api/v2/admin/fulfillment/pickup-points/{id}', tags: ['Admin fulfillment'], summary: 'Update a pickup point', security, request: { params: idParamsSchema, headers: csrf, body: json(pickupPointWriteSchema) }, responses: ok('Pickup point updated', adminPickupPointResultDataSchema) });
  registry.registerPath({ method: 'patch', path: '/api/v2/admin/fulfillment/pickup-points/{id}/active', tags: ['Admin fulfillment'], summary: 'Activate or deactivate a pickup point', security, request: { params: idParamsSchema, headers: csrf, body: json(activeSchema) }, responses: ok('Pickup point availability changed', adminActiveMutationDataSchema) });

  registry.registerPath({ method: 'get', path: '/api/v2/admin/customers', tags: ['Admin customers'], summary: 'List customers in read-only mode', security, request: { query: customerListQuerySchema }, responses: ok('Cursor page of customers', z.array(adminCustomerSummarySchema)) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/customers/{id}', tags: ['Admin customers'], summary: 'Read a customer and isolated order history', security, request: { params: idParamsSchema }, responses: ok('Customer detail', adminCustomerDetailDataSchema) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/customers/{id}/orders', tags: ['Admin customers'], summary: 'Read a cursor page of one customer orders', security, request: { params: idParamsSchema, query: cursorQuerySchema }, responses: ok('Cursor page of customer orders', z.array(adminOrderSchema)) });
  registry.registerPath({ method: 'get', path: '/api/v2/admin/audit', tags: ['Admin audit'], summary: 'List immutable redacted audit events', security, request: { query: auditListQuerySchema }, responses: ok('Cursor page of audit events', z.array(adminAuditEntrySchema)) });

  registry.registerPath({ method: 'post', path: '/api/v2/admin/shipping-zones', tags: ['Admin fulfillment'], summary: 'Compatibility alias for shipping-zone creation', deprecated: true, security, request: { headers: csrf, body: json(shippingZoneWriteSchema) }, responses: created('Shipping zone created', adminShippingZoneResultDataSchema) });
  registry.registerPath({ method: 'post', path: '/api/v2/admin/pickup-points', tags: ['Admin fulfillment'], summary: 'Compatibility alias for pickup-point creation', deprecated: true, security, request: { headers: csrf, body: json(pickupPointWriteSchema) }, responses: created('Pickup point created', adminPickupPointResultDataSchema) });
}
